[package]
name = "ducktape"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A terminal-based calendar management tool"

[dependencies]
rustyline = "11.0.0"
walkdir = "2.3.3"
ical = "0.8.0"
chrono = { version = "0.4.26", features = ["serde"] }
anyhow = "1.0.72"
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"

[dev-dependencies]
pretty_assertions = "1.3"
test-case = "3.1"
tempfile = "3.8"
