[package]
name = "ducktape"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A terminal-based calendar management tool"

[dependencies]
rustyline = "11.0.0"
walkdir = "2.3.3"
ical = "0.8.0"
chrono = { version = "0.4.26", features = ["serde"] }
anyhow = "1.0.72"
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
lru = "0.10"
once_cell = "1.8"
regex = "1.10.2"
directories = "5.0"
toml = "0.8"
chrono-tz = "0.8.6"  # Add timezone database support

[dev-dependencies]
pretty_assertions = "1.3"
test-case = "3.1"
tempfile = "3.8"
# Security-related dev dependencies
cargo-audit = "0.21.2"      # Dependency vulnerability scanning
cargo-deny = "0.15.0"       # Helps enforce license and dependency policies
cargo-udeps = "0.1.40"      # Find unused dependencies
