[package]
name = "ducktape"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "11.0.0"
walkdir = "2.3.3"
ical = "0.8.0"
chrono = "0.4.26"
anyhow = "1.0.72"
log = "0.4"
env_logger = "0.10"
