[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause", 
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "Zlib",
    "Unlicense",
    "BSL-1.0",      # Boost Software License
    "Unicode-3.0",  # Unicode License
]

[bans]
multiple-versions = "warn"
skip = [
    { name = "bitflags" },
    { name = "serde" },
    { name = "log" },
    { name = "regex" },
]

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]