excluded:
  - DucktapeDesktop/Preview Content
  - DucktapeDesktopTests
  - DucktapeDesktopUITests
  - DucktapeDesktop.xcodeproj
  - .build

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_import
  - unused_private_declaration

force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"