// This file is automatically generated by build.rs
// Do not modify this file directly

/// The current version of the DuckTape application (static reference)
pub const STATIC_VERSION: &str = "0.15.2";
