name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      
      - name: Install cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      
      - name: Run cargo-audit
        run: cargo audit
      
      - name: Run Clippy with security lints
        run: cargo clippy -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo