name: Security Audit

on:
  push:
    branches: [ main ]
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches: [ main ]
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit
      
      - name: Audit dependencies
        run: cargo audit
      
      - name: Run custom security checks
        run: |
          chmod +x security-check.sh
          ./security-check.sh

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny
      
      - name: Check dependencies
        run: cargo deny check licenses sources bans